pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Copa 2026"
include ':app'
include ':data:data'
include ':data:local'
include ':data:remote'
include ':domain'
include ':notification-scheduler'
