plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id 'dagger.hilt.android.plugin'
    id "com.google.devtools.ksp" version "1.7.20-1.0.8"
}

android {
    compileSdk 33

    defaultConfig {
        minSdk 26
        targetSdk 33
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }
}

dependencies {
    implementation project(":domain")

    // Hilt
    implementation "com.google.dagger:hilt-android:2.44"
    ksp "com.google.dagger:hilt-compiler:2.44"

    def retrofit_version = "2.9.0"
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-moshi:$retrofit_version"
    implementation("com.squareup.okhttp3:logging-interceptor:4.10.0")

    def moshi_version = "1.14.0"
    implementation "com.squareup.moshi:moshi:$moshi_version"
    implementation "com.squareup.moshi:moshi-kotlin:$moshi_version"
    ksp "com.squareup.moshi:moshi-kotlin-codegen:$moshi_version"

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")

    testImplementation("org.jetbrains.kotlin:kotlin-test:1.6.10")
}
